sudo: required

language: go
go: 
- 1.5.1
- release

stages:
- install
- compile
- test
- log

jobs:
  include:
    - stage: install
      script:
	- docker build -t tc/golang-1.9     
	- docker run -d -p 127.0.0.1:80:4567 carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec foreman start;"
	- docker ps -a
	- docker run carlad/sinatra /bin/sh -c "cd /root/sinatra; bundle exec rake test" 
    - stage: compile
      script:
      - go install
    - stage: test
      script:
      - go test -v -race -cover
    #- stage: log
     # script:
      #- travis show > build_results
