sudo: required

language: go
go: 
- 1.5.1
- release

servies:
- docker

stages:
- install
- compile
- test
- log
jobs:
  include:
    - stage: install
      script:
      - docker build --tag myimage .
      - docker run myimage
    - stage: compile
      script:
      - docker images
      - go install
    - stage: test
      script:
      - go test -v -race -cover
    #- stage: log
     # script:
      #- travis show > build_results
