language: go
go: 
- 1.5.1
- release
stages:
- compile
- test
- log
jobs:
  include:
    - stage: compile
      script:
      - go install
    - stage: test
      script:
      - go test -v -race -cover
    - stage: log
      script:
      - travis show > build_results
