#!/usr/bin/env bash
trav_stat=$(travis status)
trav_show=$(travis show)
echo -e "\n***************\nRunning post-push hook"
cd $GOPATH/src/Travis
go test
echo -e "***************\n"

if [[ $trav_stat != "started" ]]; then
	$trav_show
	echo success
fi

echo done.
